# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: npm install -g @angular/cli # runs during prebuild
    command: |
      cd josh2.0
      npm install
      ng start
      echo hello

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4200
    onOpen: open-browser
